name: Dependabot

on:
  workflow_dispatch:

  schedule:
    - cron: '30 18 * * *'

permissions: write-all

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch release branches
        run: |
          git fetch --no-tags --prune --depth=5 origin '+refs/heads/release/*:refs/remotes/origin/release/*'

      - run: |
          echo "::set-output name=matrix::$(git branch -r | grep 'origin/release/' | sed 's/origin\///' | jq -R -s -c 'split("\n")[:-1]' | head -255)"
        id: set-matrix

  dependabot-scan:
    needs: prepare
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        branch: ${{fromJson(needs.prepare.outputs.matrix)}}
    steps:
      - name: Run Dependabot
        env:
          LOCAL_GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          TARGET_BRANCH: "${{ matrix.branch }}"
          PACKAGE_MANAGER: "maven"
        run: |
          TARGET_BRANCH=$(echo "$TARGET_BRANCH" | tr -d ' ')
          echo "$TARGET_BRANCH"
          export TARGET_BRANCH=$TARGET_BRANCH
          rm -rf dependabot-core
          git clone https://github.com/tyson-trinh/dependabot-core
          cd dependabot-core
          chmod +x bin/docker-dev-shell-gh
          bin/docker-dev-shell $PACKAGE_MANAGER bin/dry-run.rb ${PACKAGE_MANAGER} ${GITHUB_REPOSITORY} --branch ${TARGET_BRANCH}