name: run test Dependabot scan

on:
  workflow_dispatch:

jobs:
  get-release-branch:
    runs-on: ubuntu-latest
    needs: check-type-update
    outputs:
      release-branch: ${{ steps.get-branch.outputs.release_branch }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch release branches
        run: |
          git fetch --no-tags --prune --depth=5 origin '+refs/heads/release/*:refs/remotes/origin/release/*'

      - name: Get release branch assigned to GitHub output
        id: get-branch
        run: |
          echo "release_branch=$(git branch -r | grep 'origin/release/' | sed 's/origin\///' | jq -R -s -c 'split("\n")[:-1]' | head -255)" >> $GITHUB_OUTPUT

  version-update:
    needs: [ get-release-branch ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ${{fromJson(needs.get-release-branch.outputs.release-branch)}}
    steps:
      - name: Checkout dependabot-core
        uses: actions/checkout@v4
        with:
          repository: tyson-trinh/dependabot-core
          ref: main
          path: dependabot-core

      - name: Export Target Branch to GITHUB_ENV
        run: |
          echo "TARGET_BRANCH=${{ matrix.branch }}" | tr -d '  ' >> $GITHUB_ENV

      - name: Echo TARGET_BRANCH
        run: echo ${{ env.TARGET_BRANCH }}

      - name: Scan version update with package maven
        env:
          LOCAL_GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PACKAGE_MANAGER: maven
        run: |
          cd dependabot-core
          sed -i 's|<CONTAINER_ARGS_HERE>|CONTAINER_ARGS=("bin/dry-run.rb" "${PACKAGE_MANAGER}" "${GITHUB_REPOSITORY}" "--branch" "${{ env.TARGET_BRANCH }}") |' bin/docker-dev-shell-gh
          chmod +x bin/docker-dev-shell-gh
          bin/docker-dev-shell-gh $PACKAGE_MANAGER

  security-update:
    needs: [ get-release-branch ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ${{fromJson(needs.get-release-branch.outputs.release-branch)}}
    steps:
      - name: Checkout dependabot-core
        uses: actions/checkout@v4
        with:
          repository: tyson-trinh/dependabot-core
          ref: main
          path: dependabot-core

      - name: Export Target Branch to GITHUB_ENV
        run: |
          echo "TARGET_BRANCH=${{ matrix.branch }}" | tr -d '  ' >> $GITHUB_ENV

      - name: Echo TARGET_BRANCH
        run: echo ${{ env.TARGET_BRANCH }}

      - name: Scan security update with package maven
        env:
          LOCAL_GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PACKAGE_MANAGER: maven
        run: |
          cd dependabot-core
          sed -i 's|<CONTAINER_ARGS_HERE>|CONTAINER_ARGS=("bin/dry-run.rb" "${PACKAGE_MANAGER}" "${GITHUB_REPOSITORY}" "--security_updates_only" "--branch" "${{ env.TARGET_BRANCH }}") |' bin/docker-dev-shell-gh
          chmod +x bin/docker-dev-shell-gh
          bin/docker-dev-shell-gh $PACKAGE_MANAGER
