name: Dependabot

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions: write-all

jobs:
  get-release-branch:
    runs-on: ubuntu-latest
    outputs:
      release-branch: ${{ steps.get-branch.outputs.release_branch }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch release branches
        run: |
          git fetch --no-tags --prune --depth=5 origin '+refs/heads/release/*:refs/remotes/origin/release/*'

      - name: Get release branch assigned to GitHub output
        run: |
          echo "release_branch=$(git branch -r | grep 'origin/release/' | sed 's/origin\///' | jq -R -s -c 'split("\n")[:-1]' | head -255)" >> $GITHUB_OUTPUT
        id: get-branch

  dependabot-scan:
    needs: get-release-branch
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        branch: ${{fromJson(needs.get-release-branch.outputs.release-branch)}}
    steps:
      - name: Set Target Branch
        run: |
          echo "TARGET_BRANCH=${{ matrix.branch }}" >> $GITHUB_ENV

      - name: Checkout dependabot-core
        uses: actions/checkout@v4
        with:
          repository: tyson-trinh/dependabot-core
          ref: main
          path: dependabot-core

      - name: Run Dependabot
        env:
          LOCAL_GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          TARGET_BRANCH: ${{ env.TARGET_BRANCH }}
          PACKAGE_MANAGER: "maven"
        run: |
          TARGET_BRANCH=$(echo "$TARGET_BRANCH" | tr -d ' ')
          echo "$TARGET_BRANCH"
          cd dependabot-core
          sed -i 's|<CONTAINER_ARGS_HERE>|CONTAINER_ARGS=("bin/dry-run.rb" "${PACKAGE_MANAGER}" "${GITHUB_REPOSITORY}" "--branch" "${TARGET_BRANCH}") |' bin/docker-dev-shell-gh
          chmod +x bin/docker-dev-shell-gh
          bin/docker-dev-shell-gh $PACKAGE_MANAGER
