name: Dependabot

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions: write-all

jobs:
  dependabot-scan:
    permissions:
      contents: write
      pull-requests: write
    runs-on: self-hosted
#    if: startsWith(github.ref, 'refs/heads/') && contains(github.ref, 'feature/')
    steps:
      - name: Extract branch name
        id: extract_branch
        run: |
          echo "GITHUB_REF=$GITHUB_REF"
          if [[ "$GITHUB_REF" == refs/heads/* ]]; then
            BRANCH_NAME=${GITHUB_REF#refs/heads/}
          elif [[ "$GITHUB_REF" == refs/pull/*/merge ]]; then
            BRANCH_NAME=$GITHUB_HEAD_REF
          fi
          echo "BRANCH_NAME=$BRANCH_NAME"
          echo "branch=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Run Dependabot
        env:
          LOCAL_GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          TARGET_BRANCH: ${{ env.branch }}
          PACKAGE_MANAGER: "maven"
        run: |
          export LOCAL_GITHUB_ACCESS_TOKEN=$LOCAL_GITHUB_ACCESS_TOKEN
          export GITHUB_REPOSITORY=$GITHUB_REPOSITORY
          export PACKAGE_MANAGER=$PACKAGE_MANAGER
          export TARGET_BRANCH=$TARGET_BRANCH
          rm -rf dependabot-core
          git clone https://github.com/tyson-trinh/dependabot-core
          cd dependabot-core
          sed -i 's|<CONTAINER_ARGS_HERE>|CONTAINER_ARGS=("bin/dry-run.rb" "${PACKAGE_MANAGER}" "${GITHUB_REPOSITORY}" "--branch" "${TARGET_BRANCH}")|' bin/docker-dev-shell-gh
          chmod +x bin/docker-dev-shell-gh
          bin/docker-dev-shell-gh $PACKAGE_MANAGER