name: Dependabot

on:
  workflow_dispatch:
  schedule:
    - '05 18 * * *'

permissions: write-all

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch release branches
        run: |
          git fetch --no-tags --prune --depth=5 origin '+refs/heads/release/*:refs/remotes/origin/release/*'

      - run: |
          echo "::set-output name=matrix::$(git branch -r | grep 'origin/release/' | sed 's/origin\///' | jq -R -s -c 'split("\n")[:-1]' | head -255)"
        id: set-matrix

  dependabot-scan:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ${{fromJson(needs.prepare.outputs.matrix)}}
    steps:
      - name: Run Dependabot
        env:
          LOCAL_GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          TARGET_BRANCH: ${{ matrix.branch }}
          PACKAGE_MANAGER: "maven"
        run: |
          export LOCAL_GITHUB_ACCESS_TOKEN=$LOCAL_GITHUB_ACCESS_TOKEN
          export GITHUB_REPOSITORY=$GITHUB_REPOSITORY
          export PACKAGE_MANAGER=$PACKAGE_MANAGER
          export TARGET_BRANCH=$TARGET_BRANCH
          rm -rf dependabot-core
          git clone https://github.com/tyson-trinh/dependabot-core
          cd dependabot-core
          sed -i 's|<CONTAINER_ARGS_HERE>|CONTAINER_ARGS=("bin/dry-run.rb" "${PACKAGE_MANAGER}" "${GITHUB_REPOSITORY}" "--branch" "${TARGET_BRANCH}")|' bin/docker-dev-shell-gh
          chmod +x bin/docker-dev-shell-gh
          bin/docker-dev-shell-gh $PACKAGE_MANAGER