name: Dependabot

on:
  push:
    branches:
      - release/check-1

permissions: write-all

jobs:
  get-release-branch:
    runs-on: ubuntu-latest
    outputs:
      release-branch: ${{ steps.get-branch.outputs.release_branch }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch release branches
        run: |
          git fetch --no-tags --prune --depth=5 origin '+refs/heads/release/*:refs/remotes/origin/release/*'

      - name: Get release branch assigned to GitHub output
        run: |
          echo "release_branch=$(git branch -r | grep 'origin/release/' | sed 's/origin\///' | jq -R -s -c 'split("\n")[:-1]' | head -255)" >> $GITHUB_OUTPUT
        id: get-branch

  version-update:
    needs: get-release-branch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ${{fromJson(needs.get-release-branch.outputs.release-branch)}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#      - name: Checkout dependabot-core
#        uses: actions/checkout@v4
#        with:
#          repository: tyson-trinh/dependabot-core
#          ref: main
#          path: dependabot-core

      - name: Echo repository to test
        run: |
          echo "${{ github.repository }}"

      - name: Echo branch to test
        run: |
          echo "${{ matrix.branch }}" | tr -d '  '

      - name: Scan version update with package maven
        env:
          LOCAL_GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PACKAGE_MANAGER: "maven"
        run: |
          ls -la
          export LOCAL_GITHUB_ACCESS_TOKEN=$LOCAL_GITHUB_ACCESS_TOKEN
          TARGET_BRANCH=$(echo "${{ matrix.branch }}" | tr -d '  ')
          echo "$TARGET_BRANCH"
          git clone https://github.com/tyson-trinh/dependabot-core
          cd dependabot-core
          sed -i 's|<CONTAINER_ARGS_HERE>|CONTAINER_ARGS=("bin/dry-run.rb" "${PACKAGE_MANAGER}" "${GITHUB_REPOSITORY}" "--branch" "${TARGET_BRANCH}") |' bin/docker-dev-shell-gh
          chmod +x bin/docker-dev-shell-gh
          bin/docker-dev-shell-gh $PACKAGE_MANAGER


#  security-update:
#    needs: get-release-branch
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        branch: ${{fromJson(needs.get-release-branch.outputs.release-branch)}}
#    steps:
#      - name: Checkout dependabot-core
#        uses: actions/checkout@v4
#        with:
#          repository: tyson-trinh/dependabot-core
#          ref: main
#          path: dependabot-core
#
#      - name: Echo branch to test
#        run: |
#          cd dependabot-core
#          echo "${{ github.repository }}"
#
#      - name: Scan security update with package maven
#        env:
#          LOCAL_GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          GITHUB_REPOSITORY: ${{ github.repository }}
#          PACKAGE_MANAGER: "maven"
#        run: |
#          TARGET_BRANCH=$(echo "${{ matrix.branch }}" | tr -d ' ')
#          echo "$TARGET_BRANCH"
#          cd dependabot-core
#          sed -i 's|<CONTAINER_ARGS_HERE>|CONTAINER_ARGS=("bin/dry-run.rb" "${PACKAGE_MANAGER}" "${GITHUB_REPOSITORY}" "--security_updates_only" "--branch" "${TARGET_BRANCH}") |' bin/docker-dev-shell-gh
#          chmod +x bin/docker-dev-shell-gh
#          bin/docker-dev-shell-gh $PACKAGE_MANAGER