name: Custom scan dependabot using re-use workflow

on:
  push:
    branches:
      - release/check-2

permissions: write-all

jobs:
  scan-matrix:
    name: Run scan for each release
    uses: ./.github/workflows/dependabot-scan.yml
    with:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      runner: ubuntu-latest
      package: maven
