name: Custom scan dependabot using re-use workflow

on:
  push:
    branches:
      - release/check-2

jobs:
  get-token:
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.get-token.outputs.token }}
    steps:
      - name: Take token
        id: get-token
        run: |
          echo "token=${{ secrets.ACCESS_TOKEN }}" >> $GITHUB_OUTPUT

  scan-matrix:
    name: Run scan for each release
    needs: get-token
    uses: ./.github/workflows/dependabot-scan.yml
    with:
      github-token: ${{ needs.get-token.outputs.token }}
      runner: ubuntu-latest
      package: maven
