name: Custom scan dependabot using reusable workflow

on:
  workflow_dispatch:

permissions: write-all

jobs:
  get-github-token:
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.get-token.outputs.token }}
    steps:
      - name: Get github access token
        id: get-token
        run: |
          echo "token=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_OUTPUT

  dependabot-scan:
    name: Run scan for each release
    needs: get-github-token
    uses: ./.github/workflows/dependabot-scan.yaml
    secrets: inherit
    with:
      github-token: ${{ needs.get-github-token.outputs.token }}
      repository: ${{ github.repository }}
      runner: ubuntu-latest
      package: maven
      version-update-only: true
      security-update-only: true
