name: Custom scan dependabot using re-use workflow

on:
  push:
    branches:
      - release/check-2

permissions: write-all

jobs:
  dependabot-scan:
    name: Run scan for each release
    uses: GCbeheo/example-java-backend/dependabot-workflow@release/check-2
    with:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      runner: ubuntu-latest
      package: maven
