name: Custom scan dependabot using reusable workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions: write-all

jobs:
  dependabot-scan:
    name: Run scan for each release
    uses: ./.github/workflows/dependabot-scan.yaml
    secrets:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      repository: ${{ github.repository }}
      runner: ubuntu-latest
      package: maven
      version-update-only: true
      security-update-only: true
